// Placeholder Supabase generated types.
// Regenerate with `supabase gen types typescript --project-id <id> > src/lib/database.types.ts`
// once the schema lands. Until then this keeps the rest of the codebase strictly typed.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

/**
 * Minimal hand-written stub of the Phase 0 schema. This file will be
 * regenerated by `supabase gen types typescript` once the migrations
 * are applied. Until then, only tables that the foundation code
 * actually touches are declared here, and only with the columns it
 * actually reads — keeping `strict` happy without lying about shape.
 */
export type Database = {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          user_id: string;
          facility_id: string;
        };
        Insert: {
          user_id: string;
          facility_id: string;
        };
        Update: {
          user_id?: string;
          facility_id?: string;
        };
        Relationships: [];
      };
      facility_config: {
        Row: {
          facility_id: string;
          module: string;
          key: string;
          value: Json;
        };
        Insert: {
          facility_id: string;
          module: string;
          key: string;
          value: Json;
        };
        Update: {
          facility_id?: string;
          module?: string;
          key?: string;
          value?: Json;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
