import "server-only";

import { jsPDF } from "jspdf";

const NAVY: [number, number, number] = [0, 59, 111]; // #003B6F
const GREEN: [number, number, number] = [77, 255, 0]; // #4DFF00
const GREY: [number, number, number] = [165, 172, 175]; // #A5ACAF

export const PAGE = {
  width: 8.5,
  height: 11,
  margin: 0.6,
} as const;

export interface HeaderOpts {
  facilityName: string;
  reportTitle: string;
  dateRange: string;
  pageNum: number;
  totalPages: number;
}

export function addHeader(doc: jsPDF, opts: HeaderOpts): void {
  // Navy bar
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, PAGE.width, 0.7, "F");
  // Green accent line
  doc.setFillColor(...GREEN);
  doc.rect(0, 0.7, PAGE.width, 0.04, "F");
  // White text in the bar
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(opts.facilityName, PAGE.margin, 0.45);
  doc.setFont("helvetica", "normal");
  doc.text(opts.reportTitle, PAGE.width / 2, 0.45, { align: "center" });
  doc.setFontSize(8);
  doc.text(opts.dateRange, PAGE.width - PAGE.margin, 0.45, { align: "right" });
  // Page N of M (bottom right)
  doc.setTextColor(...GREY);
  doc.setFontSize(8);
  doc.text(
    `Page ${opts.pageNum} of ${opts.totalPages}`,
    PAGE.width - PAGE.margin,
    PAGE.height - 0.3,
    { align: "right" },
  );
  // Reset text color for caller
  doc.setTextColor(0, 0, 0);
}

export function addFooter(
  doc: jsPDF,
  opts: { generatedAt: string; generatedBy: string },
): void {
  doc.setTextColor(...GREY);
  doc.setFontSize(7);
  doc.text(
    `Generated by RinkReports on ${opts.generatedAt} by ${opts.generatedBy}`,
    PAGE.margin,
    PAGE.height - 0.3,
  );
  doc.setTextColor(0, 0, 0);
}

export function addSignaturePage(
  doc: jsPDF,
  opts: { preparedBy: string; reviewedBy: string },
): void {
  doc.addPage();
  let y = PAGE.height / 2 - 1;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Prepared by:", PAGE.margin, y);
  doc.line(PAGE.margin + 1.2, y, PAGE.margin + 4.5, y);
  doc.text("Date:", PAGE.margin + 4.8, y);
  doc.line(PAGE.margin + 5.4, y, PAGE.margin + 7.4, y);
  y += 0.8;
  doc.text("Reviewed by:", PAGE.margin, y);
  doc.line(PAGE.margin + 1.2, y, PAGE.margin + 4.5, y);
  doc.text("Date:", PAGE.margin + 4.8, y);
  doc.line(PAGE.margin + 5.4, y, PAGE.margin + 7.4, y);

  // Silence unused-parameter lint — names are pre-filled if provided
  void opts.preparedBy;
  void opts.reviewedBy;
}

export function addSectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setTextColor(...NAVY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(title, PAGE.margin, y);
  doc.setDrawColor(...NAVY);
  doc.setLineWidth(0.01);
  doc.line(PAGE.margin, y + 0.05, PAGE.width - PAGE.margin, y + 0.05);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
  return y + 0.3;
}

export function newPageIfNeeded(
  doc: jsPDF,
  currentY: number,
  requiredHeight: number,
  header: HeaderOpts,
): number {
  if (currentY + requiredHeight > PAGE.height - 0.6) {
    doc.addPage();
    addHeader(doc, { ...header, pageNum: header.pageNum + 1 });
    return PAGE.margin + 0.9;
  }
  return currentY;
}

export function docToBase64(doc: jsPDF): string {
  const datauri = doc.output("datauristring");
  return datauri.split(",")[1] ?? "";
}
